const GET_CHARACTERS = "GET_CHARACTERS";
const GET_EPISODES = "GET_EPISODES";
const GET_CHARACTER_DETAIL = "GET_CHARACTER_DETAIL";
const FILTER_ORIGIN = "FILTER_ORIGIN";
const CLEAR_PAGE = "CLEAR_PAGE";

module.exports = {
  GET_CHARACTERS,
  
}